export const APP_ACTIONS = {
  NAVIGATE_TO: "NAVIGATE_TO",
  SHOW_LOADING: "SHOW_LOADING",
  HIDE_LOADING: "HIDE_LOADING",

  MUTATION: {
    UPDATE_APP_STATE: "UPDATE_APP_STATE",
    RESET_APP_STATE: "RESET_APP_STATE",
  },
};

export const AUTH_ACTIONS = {
  SIGN_IN: "SIGN_IN",
  SIGN_UP: "SIGN_UP",
  SIGN_OUT: "SIGN_OUT",

  RESULT: {
    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
    SIGN_IN_ERROR: "SIGN_IN_ERROR",
    SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
    SIGN_UP_ERROR: "SIGN_UP_ERROR",
  },
};
