export const APP_ACTIONS = {
  START_BOOT_INIT: "START_BOOT_INIT",
  SHOW_POPUP: "SHOW_POPUP",

  MUTATION: {
    UPDATE_APP_STATE: "UPDATE_APP_STATE",
    RESET_APP_STATE: "RESET_APP_STATE",
  },
};

export const AUTH_ACTIONS = {
  SIGN_IN: "SIGN_IN",
  SIGN_UP: "SIGN_UP",
  SIGN_OUT: "SIGN_OUT",

  MUTATION: {
    UPDATE_AUTH_STATE: "UPDATE_AUTH_STATE",
    RESET_AUTH_STATE: "RESET_AUTH_STATE",
  },
};

export const SUBSCRIPTION_ACTIONS = {
  FETCH_ALL: "FETCH_ALL",

  MUTATION: {
    UPDATE_SUBSCRIPTION_STATE: "UPDATE_SUBSCRIPTION_STATE",
    RESET_SUBSCRIPTION_STATE: "RESET_SUBSCRIPTION_STATE",
  }
};
